<?php
require_once $_SERVER["DOCUMENT_ROOT"]."/_code/includes/_config.php";
require_once $_SERVER["DOCUMENT_ROOT"]."/_code/includes/_conexion.php";
require_once $_SERVER["DOCUMENT_ROOT"]."/_code/modelos/Persona.php";
//echo __FILE__."<br/>";
class Alumno extends Persona{
    private $fecha_nacimiento;
    private $pde;
    private $id_religion;
    private $grado_educacional_padre;
    private $grado_educacional_madre;
    private $persona_vive;

    private $estado = "1";

    public function set_fecha_nacimiento($fecha_nacimiento)
    {
        $this->fecha_nacimiento = $fecha_nacimiento;
    }
    public function get_fecha_nacimiento()
    {
        return $this->fecha_nacimiento;
    }
    public function set_grado_educacional_madre($grado_educacional_madre)
    {
        $this->grado_educacional_madre = $grado_educacional_madre;
    }
    public function get_grado_educacional_madre()
    {
        return $this->grado_educacional_madre;
    }
    public function set_grado_educacional_padre($grado_educacional_padre)
    {
        $this->grado_educacional_padre = $grado_educacional_padre;
    }
    public function get_grado_educacional_padre()
    {
        return $this->grado_educacional_padre;
    }
    public function set_id_religion($id_religion)
    {
        $this->id_religion = $id_religion;
    }
    public function get_id_religion()
    {
        return $this->id_religion;
    }
    public function set_pde($pde)
    {
        $this->pde = $pde;
    }
    public function get_pde()
    {
        return $this->pde;
    }
    public function set_persona_vive($persona_vive)
    {
        $this->persona_vive = $persona_vive;
    }
    public function get_persona_vive()
    {
        return $this->persona_vive;
    }

    public function set_identidad($run, $nombre1, $nombre2, $apellido1, $apellido2, $sexo, $id_direccion, $email)
    {
        parent::set_identidad($run, $nombre1, $nombre2, $apellido1, $apellido2, $sexo, $id_direccion, $email); // TODO: Change the autogenerated stub

    }

    public function to_matriz()
    {
        $matriz = parent::to_matriz();
        $matriz["fecha_nacimiento"] = $this->get_fecha_nacimiento();
        $matriz["pde"] = $this->get_pde();
        $matriz["id_religion"] = $this->get_id_religion();
        $matriz["grado_educacional_padre"] = $this->get_grado_educacional_padre();
        $matriz["grado_educacional_madre"] = $this->get_grado_educacional_madre();
        $matriz["persona_vive"] = $this->get_persona_vive();

        return $matriz;
    }


    public function to_json(){
        $json = json_encode($this->to_matriz(), JSON_UNESCAPED_UNICODE);
        return $json;
    }

    public function db_get_alumno_by_run(){
        $run_alumno = $this->get_run();

        global $myPDO;
        $sentencia = $myPDO->prepare("CALL get_alumno_by_run(?)");
        $sentencia->bindParam(1, $run_alumno, \PDO::PARAM_STR, 9);
        $sentencia->execute();

        $data = $sentencia->fetchAll(0);
        foreach($data as $row){
            $this->set_identidad(
                $row["run_alumno"],
                $row["nombre1"],
                $row["nombre2"],
                $row["apellido1"],
                $row["apellido2"],
                $row["sexo"],
                $row["id_direccion"],
                $row["email"]
            );
            $this->set_avatar($row["avatar"]);
            $this->set_fecha_nacimiento($row["fecha_nacimiento"]);
            $this->set_pde($row["pde"]);
            $this->set_id_religion($row["id_religion"]);
            $this->set_grado_educacional_padre($row["grado_educacional_padre"]);
            $this->set_grado_educacional_madre($row["grado_educacional_padre"]);
            $this->set_persona_vive($row["persona_vive"]);
        }

        return $sentencia->rowCount();

    }


}
?> 